language: scala
sudo: false

env:
  global:
    - JDK6=zulu@1.6.107
    - JABBA_HOME=/home/travis/.jabba

jdk: oraclejdk8

jobs:
  include:
    - stage: test
      script:
        - $JABBA_HOME/bin/jabba install "$JDK6"
        - export JAVA_HOME="$JABBA_HOME/jdk/$JDK6"
        - export PATH="$JAVA_HOME/bin:$PATH"
        - java -version
        - sbt test scripted

    - stage: test
      script: sbt ^^1.0.0 test scripted

    - stage: deploy-sbt-0.13
      script: skip
      deploy:
        provider: script
        script:
          - $JABBA_HOME/bin/jabba install "$JDK6"
          - export JAVA_HOME="$JABBA_HOME/jdk/$JDK6"
          - export PATH="$JAVA_HOME/bin:$PATH"
          - java -version
          - sbt publish
        on:
          tags: true
          repo: sbt/sbt-bintray

    - stage: deploy-sbt-1.0
      script: skip
      deploy:
        provider: script
        script: sbt ^^1.0.0 publish
        on:
          tags: true
          repo: sbt/sbt-bintray

before_install:
  - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.10.1/install.sh | bash && . ~/.jabba/jabba.sh

install:
  - curl -L --fail https://piccolo.link/sbt-0.13.17.tgz > sbt-0.13.17.tgz
  - tar zxf ./sbt-0.13.17.tgz -C $HOME/
  - export PATH="$HOME/sbt/bin:$PATH"
  - export SBT_OPTS="-Xms2048M -Xmx2048M -Xss2M -XX:MaxPermSize=512M"
  - sbt about

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

env:
  global:
    # travis encrypt BINTRAY_USER=...
    - secure: "eo+yjPcu9FZnK4ZhR5hGo6ZmWAyp2rwm1/KmaTyVcc9DMhn4YWv5DlxsnkVcPvX+RXOOSMy3zh+kK3PKRCsNSWGNICUulP5XmOT1cR55X3455kvRvzUzIXKlapw/jPU8eo+ak/g/KlWGql6y254oQfMZL5cNoC8GMfT8vLFIQhE="
    # travis encrypt BINTRAY_PASS=...
    - secure: "jTaZa7TqL/Kev8WZPvqaJXaI4aMLfPua4SZo9fFbUvSob1+m09cDgS33VDohq+d45n/+gSDCHePSm2/tDlqti3utM/9X3xkzUhn3kJM/70Rq1cCmBsPlnFCpnDoGYPOCBskTo1dVbmab0WIpdUtfETTe6+3jlu7ijFfXaR7Yy3c="

