language: scala
jdk: openjdk8

jobs:
  include:
    - stage: test
      script: sbt test scripted

    - stage: deploy-sbt-1.0
      script: skip
      deploy:
        provider: script
        script: sbt publish
        on:
          tags: true
          repo: sbt/sbt-bintray

before_cache:
  - find $HOME/.cache/coursier/v1 -name "ivydata-*.properties" -delete
  - find $HOME/.ivy2              -name "ivydata-*.properties" -delete
  - find $HOME/.sbt               -name "*.lock"               -delete
  - rm -r $(find $HOME/.sbt/boot -name "*-SNAPSHOT") || true

cache:
  directories:
    - $HOME/.cache/coursier/v1
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

env:
  global:
    # travis encrypt BINTRAY_USER=...
    - secure: "eo+yjPcu9FZnK4ZhR5hGo6ZmWAyp2rwm1/KmaTyVcc9DMhn4YWv5DlxsnkVcPvX+RXOOSMy3zh+kK3PKRCsNSWGNICUulP5XmOT1cR55X3455kvRvzUzIXKlapw/jPU8eo+ak/g/KlWGql6y254oQfMZL5cNoC8GMfT8vLFIQhE="
    # travis encrypt BINTRAY_PASS=...
    - secure: "jTaZa7TqL/Kev8WZPvqaJXaI4aMLfPua4SZo9fFbUvSob1+m09cDgS33VDohq+d45n/+gSDCHePSm2/tDlqti3utM/9X3xkzUhn3kJM/70Rq1cCmBsPlnFCpnDoGYPOCBskTo1dVbmab0WIpdUtfETTe6+3jlu7ijFfXaR7Yy3c="
